version: '3.8'

services:
  # Backend FastAPI Service (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wakili-backend-dev
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - ./docs:/app/docs
      - ./chats:/app/chats
      - ./exports:/app/exports
    networks:
      - wakili-network-dev
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend Next.js Service (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: wakili-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - wakili-network-dev
    restart: unless-stopped
    command: ["npm", "run", "dev"]

networks:
  wakili-network-dev:
    driver: bridge

volumes:
  docs:
  chats:
  exports: